mob:

        joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100
        
        left_wheel_joint_effort_controller:
                type: effort_controllers/JointEffortController
                joint: left_wheel_joint
                
        right_wheel_joint_effort_controller:
                type: effort_controllers/JointEffortController
                joint: right_wheel_joint
